steps:
  # ... existing steps ...

  # Déploiement sur Cloud Run avec le secret
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'vinyl-selector'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vinyl-selector'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--set-secrets'
      - 'DISCOGS_API_TOKEN=discogs-token:latest' 